site_name: Sheep
site_author: Guillaume Giamarchi, Mathilde Hermet

extra_css: [css/codehilite.css]

theme:
  name: readthedocs
  highlightjs: false

nav:
  - Home: index.md
  - quickstart.md
  - sheep-live.md
  - bootloader.md
  - Configuration:
      - config.md
      - config_lin.md
      - config_env.md
      - config_net.md
      - config_example.md
  - Miscellaneous:
      - internals.md
      - pxe-pilot.md

markdown_extensions:
  - admonition
  - codehilite
